name: Daily e2e tests
"on":
  # allows manual run on github actions
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  end-to-end-tests:
    name: End to end tests
    strategy:
      matrix:
        grafana-image-tag:
          # OnCall doesn't work on the following versions of Grafana
          # - 8.5.22
          # - 9.0.0
          # - 9.1.0

          # 9.2.0 is the earliest version where things work
          - 9.2.20
          - 9.3.16
          - 9.4.13
          - 9.5.7
          - 10.0.2

          # NOTE: don't run on > 10.0.3 until this issue is fixed. It appears that something was changed
          # with the plugin-proxy that caused it to start throwing HTTP 502s from time to time
          # https://raintank-corp.slack.com/archives/C01C4K8DETW/p1692279329797149
          # - latest
      fail-fast: false
    uses: ./.github/workflows/e2e-tests.yml
    with:
      grafana-image-tag: ${{ matrix.grafana-image-tag }}
      run-expensive-tests: false
    secrets: inherit

  post-status-to-slack:
    runs-on: ubuntu-latest
    needs: end-to-end-tests
    if: always()
    steps:
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: irm-amixr-flux
          # yamllint disable rule:line-length
          payload: |
            {
              "text": "Daily e2e tests build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Daily e2e tests build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
          # yamllint enable rule:line-length
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DAILY_E2E_TESTS_BOT_TOKEN }}
